project_id = "toquetin"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
enable_signup = false
enable_anonymous_sign_ins = true
